### ISSUE TITLE
Broken dependency coming from web3

### ISSUE THREAD

**Issue by dmihal** [OpenZeppelin/openzeppelin-test-environment#126]
When I try to run my tests, i get this:

```Error: Cannot find module 'scrypt-shim'```

This appears to come from web3: ethereum/web3.js#3210

This library has a fixed webpack version 1.2.2. Updating the version or making it a peer dependency should resolve this issues.

**Comment by ylv-io** [comment]
He @dmihal ! Thanks for reporting the issue. I am a bit confused. You mentioned webpack a couple times in your post but `test-env` doesn't use webpack at all. Do you mean web3 library instead?

**Comment by dmihal** [comment]
Thanks @ylv-io, that seems to be a typo on my part. I've changed it to web3.

**Comment by abcoathup** [comment]
Hi @dmihal!  I’m sorry that you had this issue.  We would need more information so that we can reproduce it.

Can you advise the operating system, node and npm versions that you are using? Any other details that might help us reproduce it would be appreciated!  

I tried reproducing with a simple environment on WSL2 but didn't get any errors.
This was also reported by another community member in the community forum:
https://forum.openzeppelin.com/t/cannot-find-module-scrypt-shim-when-using-openzeppelin-test-environment/3147

**Comment by frangio** [comment]
Can this issue be reproduced in Node 10 or 12?

**Comment by abcoathup** [comment]
I wasn't able to reproduce in node v10.21.0 or node v12.18.2
I could only reproduce in node 11 which is no longer a node supported release.

**Comment by frangio** [comment]
Okay. Thank you! Closing this issue then.

**Comment by lyledavids** [comment]
Hi, I am getting the same error. Node v10.15.3
Any fix yet

**Comment by arsenyjin** [comment]
Having the same issue with `Node v10.6.0`

**Comment by frangio** [comment]
@lyledavids @arsenyjin Can you try upgrading your Node version to `10.21.0`?
